### PR TITLE
Add a few protected rooms

### PR DESCRIPTION
**Pull request by stkent**
@maschall these are some rooms that it would seem valuable to permanently keep open, even if there are long periods of silence. I started by adding just a few I'm a member of so I can see how the change works and is received. If successful, maybe we can consider cautiously expanding the list.

### CODE REVIEW

**Comment by maschall** [comment]
A couple things:

We've been using the Heroku configuration settings to do this, but I do like the idea of having some means of discussing what should and shouldn't be ignored, but I think it makes sense to keep using the Heroku configuration, instead of committing it.

I understand and agree `offboarding` should be ignored, not really sold on the other two.  `meet-ups` makes sense somewhat, but I feel like having monthly meetings already, that room should be more popular than it is.

We did make a regex for T&D team to keep their rooms around.  I'm wondering if we prefixed `dl_` or `dl-` to the names to keep them around.  so `dl-offboarding` may make sense.  (not sold on this but throwing it out as an alternative)

Finally, I'm thinking maybe we should bump up the time to 60 days for warning and 90 days archive.  Especially for holiday times coming up.

**Comment by stkent** [comment]
Ah, yeah, non-committed is easier. It might be a good idea to add a note to the README that indicates we use Heroku to manage our ignorelist?

I'm good to just protect `offboarding` for now, and let the others see how the new limits:

> 60 days for warning and 90 days archive

work for them.

**Comment by stkent** [comment]
Pattern updated to `^td-,^td-,offboarding`; not sure if the `td` pattern repeat is intentional or not, but 🤷‍♂️

**Comment by maschall** [comment]
ha, the problem is that the app expects the ENV to be an array comma delimited, but python doesn't know if it's an array of 1 or a string, so the double up was to force it to be an array.

**Comment by stkent** [comment]
Hah, that's hilarious!

**Pull request closed without merging**
